### ISSUE TITLE
Should the Google Fonts Latin African contain dieresisbelowcomb?

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/glyphsets#119]

**Comment by vv-monsalve** [comment]
Hi Eben, could you please provide more context on this issue? Is it meant for tracking purposes for inclusion or for discussing the possibility?

**Comment by moyogo** [comment]
U+0324 is used under u and w in the Gabon scientific alphabet so its omission seems to a mistake, this may have been because there's no clear usage. Do you have an example in your corpus analysis?

For Global Latin it definitely should be included as it is used in the Kayah Latin orthography under vowels and in Minbei,Minding or Puxian under some vowels.

More generally it is also used in IPA or in academic transliterations.

**Comment by EbenSorkin** [comment]
Vivi, the context was that I seemed to notice that there was one or more letter glyphs included in the SSA glyph set that needed the diacritic if they were going to be made of components, but the diacritic itself wasn't present in the Glyphs list for SSA. It looked like an accidental oversight.

**Comment by EbenSorkin** [comment]
The Glyphs in the SSA now that would use this are udieresisbelow and Udieresisbelow

**Comment by vv-monsalve** [comment]
Ah ok, so this is to follow up the inclusion :)

> For Global Latin it definitely should be included as it is used in the Kayah Latin orthography under vowels and in Minbei,Minding or Puxian under some vowels.

Denis, do you know the population or how many speakers of these languages are? Currently, Latin Core is defined for languages with >5MM speakers. If lower, they should go to Latin Beyond.

**Comment by moyogo** [comment]
@vv-monsalve these are not European or North American languages, so they are irrelevant for Latin Core.

**Comment by EbenSorkin** [comment]
Should this stay in Latin SSA or go to beyond or is there sometimes an
overlap? If there is should there be?

**Comment by moyogo** [comment]
> Should this stay in Latin SSA or go to beyond or is there sometimes an
overlap? If there is should there be?

I guess.
I don’t know what the requirements for Latin SSA are.

But based on (GF_glyphsets/Latin/README.md)[https://github.com/googlefonts/glyphsets/blob/fc6ae68479bb7c0913f843aecc675018911fd11d/GF_glyphsets/Latin/README.md]: "African: support for Latin African languages not supported by Latin Core" and "Beyond: support for indigenous latin based languages from European and American regions (< 5M peakers), that are not supported in Latin Core", since ṳ and w̤ are used in Fang-Ntumu and Fang-Nzaman in the Gabon Scientific Alphabet it would make sense to include them in GF_Latin_African even if there’s no large evidence of use unlike for some other languages.
Asian languages (like Kayah, Minbei, Mindong, Puxian) are not mentioned in any of the Latin set definitions (besides the Vietnamese set).

**Comment by EbenSorkin** [comment]
I’ll check if w̤ is in Latin African now. I think it isn’t. Maybe we need
that and the diacritic mark. 😀

**Comment by EbenSorkin** [comment]
I checked, and the w̤ is not in the GF African either.

So I amend my request to 1)include that letter in GF African too and 2) the
diacritic U+0324 and now.

I am not seeing that there is a such a thing as upper case w̤ but It seemed
worthwhile asking about it. When I make it programmatically in Glyphs no
unicode is there so it probably does not exist. But better safe than sorry.

Related: There is already an uppercase Udieresisbelow with a unicode of
U+1E72 in GF African which would also use the diacritic U+0324.

**Comment by moyogo** [comment]
@EbenSorkin I opened the PR #122.
I left W̤ and w̤ out because they are always composed of two characters, with U+0324.

With modern font shapers there is no need for a single glyph as the dieresiscomb can be positioned with an anchor and the GPOS mark feature.
There are hundreds of Latin orthography letters composed with two or more characters with base letter and combining marks, there is no reason this one should be treated differently.

**Comment by EbenSorkin** [comment]
Ok so both uc and lc should be made with camp. And only the diacritic
should be added to Gf African
