### ISSUE TITLE
Unencoded Glyphs Missing from /data/results/ .glyphs files

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/glyphsets#166]
Trying to wrap my head around the new glyphsets tool. I looked in the [/data/results](https://github.com/googlefonts/glyphsets/blob/main/data/results/) .glyphs files but many of the unencoded glyphs from the previous glyph sets are missing, for example in [GF_Latin_Plus.glyphs](https://github.com/googlefonts/glyphsets/blob/main/data/results/glyphs/GF_Latin_Plus.glyphs), the sets of numerals (*.tf *.numr, *.dnom) are no longer there. 

Should I just refer to the archived .glyphs character sets for now?

**Comment by yanone** [comment]
The changes should have been preserved. I'll investigate this. This looks like a mistake. There may be more glyphs missing from other glyphsets, so I'll go over them one by one another time.

In the meantime, rather than looking into the "Archive" folder, it's better to go back in time of the repository. This file version from half a year ago should be unchanged from what you know: https://github.com/googlefonts/glyphsets/blob/50f81f78473d9c72e4d19ddf378a7c532c4e86ad/GF_glyphsets/Latin/glyphs/GF_Latin_Plus.glyphs

**Comment by yanone** [comment]
I found missing unencoded glyphs for Latin_Plus and Latin_Vietnamese and [added them back](https://github.com/googlefonts/glyphsets/commit/584d9ad4dacc731b748c7f8ab8a31230db47495d). 
Thanks for catching that.
I won't publish a new package right away as I'm about to make more changes, but the updated files are now available in the `/data/results` folder.
