### ISSUE TITLE
What are "icapitalsmall" and "D.circled" for?

### ISSUE THREAD

**Issue by AndreasFaust** [googlefonts/glyphsets#252]
There are 2 strange glyphs in the Latin glyph sets that make me wonder what they are for:
1. "D.circled" in "Latin Plus"
2. "icapitalsmall" in "Latin Beyond" (no Unicode!)

Can anybody help?

**Comment by yanone** [comment]
`D.circled` was recently added. It's used for "Protected Design" similar to "Copyright".

`icapitalsmall` is part of some African languages and we already support it in the **GF_Latin_African** glyphset. Please note that we’re in the process of (slowly over time) reworking all the glyphsets to use language definitions (denoted by the green or red mark in https://github.com/googlefonts/glyphsets/blob/main/GLYPHSETS.md) because the previous manual assembly approach was too error-prone. So it's possible that the old-school glyphsets such as **GF_Latin_Beyond** contain several glyphs that will eventually disappear from it.

**Comment by AndreasFaust** [comment]
Thank you for explaining, @yanone! 
I’m curious: As I understand it, "Latin Plus", "Beyond" etc. will be removed and web developers will have to bundle languages manually? Or are demanded glyphs automatically determined by the Google Font API?

**Comment by yanone** [comment]
I see where you're coming from now.

The Google Fonts API are using _subsets_ which are different from the _glyphsets_ defined here. Even though they both contains glyphset definitions, they serve different purposes.

I've added an explanation to the [README](https://github.com/googlefonts/glyphsets) of the glyphsets repo to the best of my abilities, but I'm not firm in how subsets are defined or used. I'm involved with the _font authoring_ side, which this repository now solely serves.

I've asked internally what the logic is behind definitions of subsets to be served by the GF API but haven't received a conclusive answer yet.
