### ISSUE TITLE
Provide graphical representation for GF list

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/glyphsets#39]
Is it possible to provide pictures, graphics, or PDF version of glyph representation with example rendering of the glyphs? This will benefit beginners such as for localized glyphs, ligatures, and/or diacritics placement.

**Comment by NightFurySL2001** [comment]
As there is a new update, it would be advisible to provide a glyph representation list which will be of immense help for font developers to refer to as most designers are not familiar with Vietnamese, African and Minorities character set, or at least a list of notable issues during implementation.

**Comment by simoncozens** [comment]
I don't think this is feasible (and certainly not in scope for this repository).

The problem with providing an example glyph is that it's not sufficient for a design to understand how to contextualise that character for their font, and it does not substitute for the kind of research and engagement needed to *respectfully* design a font for a language's requirements. Designers who want to work with Vietnamese should go and do good research (for example, Donny Truong's "Vietnamese Typography") rather than thinking they can get everything they need just by looking at an exemplar.

I think there is some work that's happening to provide information about what to do and what not to do for African languages. But in general I would prefer to discourage people from "filling in" codepoints just to achieve glyphset coverage without really understanding what's required.
