### ISSUE TITLE
Extended Arabic -- how can I help?

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/glyphsets#68]
IIUC, getting the nam files in the [Lib/glyphsets/encodings](https://github.com/googlefonts/glyphsets/tree/main/Lib/glyphsets/encodings) directory extended is one key to supporting the Arabic Supplement and Arabic Extended A/B blocks in Google Fonts API and thus provide support for a whole bunch of languages that need these characters.

However I'm slightly confused about how these files work in practice. I see the Latin script model where there are `latin` and `latin-ext` subsets (corresponding approximately, but not exactly, to [latin_unique-glyphs.nam](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/latin_unique-glyphs.nam) and [latin-ext_unique-glyphs.nam](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/latin-ext_unique-glyphs.nam)) where the two subsets have very little overlap:

```
/* latin */
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
```
vs
```
/* latin-ext */
unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
```  

But it doesn't seem to me like the same model (i.e. creating `arabic-ext` subset to go with the `arabic` one) could work very well for Arabic because (again, iiuc) each GF subset is presented to consumers (browsers, etc) as a separate font resource, thus causing font run boundaries every time characters from one subset are adjacent to characters from another, and font run boundaries generally stop contextual shaping which is critical for Arabic script.

I've only just barely stuck my toes in so I'm sure there is plenty I don't understand, but I guess my questions are: what is the plan for supporting Arabic Supplement and Arabic Extended A/B blocks and is there something we can do to help move this forward?

**Comment by LornaSIL** [comment]
Is there anything we can do to add an `arabic-ext` so that other languages can use Google fonts?

**Comment by vv-monsalve** [comment]
Hi @bobh0303 and @LornaSIL,

Thank you for being so interested in contributing to improving Arabic support. We are currently reviewing the entire glyph set definition with the goal of updating subsets and the whole ecosystem of language support in GF from there.

Regarding complex scripts and Arabic in particular, IIUIC the main concern so far has been the different implementations to support them, which tend to differ greatly among developers.

cc @moyogo @simoncozens @RosaWagner @chrissimpkins

**Comment by bobh0303** [comment]
Thanks, @vv-monsalve, for your reply.

> We are currently reviewing the entire glyph set definition with the goal of updating subsets and the whole ecosystem of language support in GF from there.

This is good news. Is the discussion in public where we could monitor and/or participate?

**Comment by RosaWagner** [comment]
The conversation happens in this repo :) We haven't tackled the arabic script yet but you could eventually propose a .glyphs file which would complete https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Arabic/glyphs. Or even correct the existing ones. It would be definitely welcome.

We could then harmonise the existing API subset definition (.nam files) with these glyphsets. Creating a new subset (arabic-ext unique nam file) may be complicated, but worth considering.

**Comment by vv-monsalve** [comment]
Yes, please, you could edit the main Arabic file that Rosa pointed out to present the changes on what would be the "Arabic-Core" and perhaps also create one to propose the "Arabic-Ext".

Bear in mind that the idea beneath the current system is modularity so that each of glyph set works as modules that can be combined to achieve higher language support (per font project requirements). For more context, you could read the entrance we have added to the [GF Guide about Glyphsets](https://googlefonts.github.io/gf-guide/requirements.html#glyphsets).

Then feel free to open PR with the changes submission as well as issues providing details on the proposals, to continue elaborating on them.

**Comment by bobh0303** [comment]
> Bear in mind that the idea beneath the current system is modularity so that each of glyph set works as modules that can be combined to achieve higher language support (per font project requirements).

This is exactly the problem I pointed out at the start of this post, namely that, for many scripts (including Arabic), glyph sets can't be treated as building blocks to be combined together -- at least not with the current implementation. This is because each glyph set results in a _separate font resource_ downloaded to the browser, creating run-breaks between characters in separate glyphsets.  As a result, required contextual behaviors that cross those boundaries won't work -- in fact the logic in the original font that implemented such contextual behavior is probably omitted from both font resources during subsetting since neither subset contained both the glyphs in question.

As a specific example, consider the required ligation between lam-like characters and alef-like characters in arabic script. The plain alef (U+0627) is, of course, in the basic `arabic` subset. There are, as of Unicode 15, eight different lam-like characters only 5 of which are in the basic `arabic` subset. If we implement an `arabic-ext` subset and includes in it the other three lam-like characters, then _neither_ of downloaded GF font resources (the `arabic` or `arabic-ext`) can possibly contain the lam-alef ligature code for those three lam characters since neither subset has both the plain alef AND the other three lam glyphs -- thus no ligation is possible.

The assumption GF is making -- that fonts can be broken up into modular subsets, downloaded separately and then still be functional -- is not valid. 

How do we solve this problem?

**Comment by bobh0303** [comment]
Hi Rosa, 

> GF_glyphsets are only there to guide designers on language support etc, they have nothing to do with the API

It is good to clarify this distinction.

I and my colleagues (and this issue) are concerned about the API, and specifically what is delivered to browsers wanting to use an Arabic font from Google Fonts via that API. When Viviana talked about "building blocks", my mind shifted to the `latin` and `latin-ext` subsets delivered by the API which are, more or less, treated as building blocks: users can request just the `latin` subset or that plus the `latin-ext` subset.  Using such a building-block approach in the API [as currently implemented] cannot work for Arabic (and other non-Roman) scripts as I've described above. From the beginning of this thread, this is the problem I've been trying to express (and seek solutions for)-- I apologize if I've not been clear enough. 

> the .nam in `Lib/encoding` 

I assume you mean [Lib/glyphsets/encodings](https://github.com/googlefonts/glyphsets/tree/main/Lib/glyphsets/encodings) 

> are a sensitive database. 

I'm not sure what you mean by _sensitive_, but I guess the initial question in my mind is:  are these `.nam` files what drives the font subsetting for purposes of delivering Google Fonts to browsers via the API?

**Comment by RosaWagner** [comment]
> I'm not sure what you mean by sensitive, but I guess the initial question in my mind is: are these .nam files what drives the font subsetting for purposes of delivering Google Fonts to browsers via the API?

Yes. 

If according to you an arabic-ext subset doesn't make sense, then better to keep stuff as they already are and just adding the missing glyphs in the existing unique subset definition for arabic — so these glyphs don't get subsetted from the font in the API.

Now in term of methodology: please give us a list of missing glyphs (unicodes or prod names). From that we will define a nice glyphset to complete our collection so other designers can benefit from that + we will make sure the API-subset is updated as well.

**Comment by vv-monsalve** [comment]
I apologize I didn't make that clarification between Glyphsets and the purposes + function of .nam files. 

> From that we will define a nice glyphset to complete our collection so other designers can benefit from that + we will make sure the API-subset is updated as well.

Sounds good. Let's continue improving the Arabic support.

**Comment by bobh0303** [comment]
> Now in term of methodology: please give us a list of missing glyphs (unicodes or prod names). 

Sorry for my delay in responding. My difficulty is that I can't figure out which Arabic Unicode chars other than presentation forms to omit. The chars defined by Unicode are there for support of various languages and writing conventions, so by what criteria does one decide some characters defined in Unicode should not be included?

**Comment by simoncozens** [comment]
Okay. I now (better) understand the problem here, and in other glyphsets issues.

* This repo contains two sets of files: glyphsets, which are what we give to designers when we're asking them to make a font; and nam files, which are sets of Unicode codepoints that logically belong together.
* We talk about the nam files as being used for "subsetting", but that's an unhelpful conceptualisation. The nam files are used by the fonts.google.com front-end to shard a font into multiple sub-fonts, so that these can be delivered via CSS in smaller chunks. If the browser only loads the sub-fonts that are needed for a document, we typically save lots of bytes serving the sub-fonts instead of the whole font.
* We currently have e.g. `latin_unique-glyphs` and `latin-ext_unique-glyphs`, so that people who are just using a basic Latin don't have to pay the penalty of downloading a whole Latin Ext font as well. We also have `greek-ext` and `cyrillic-ext`. This tempts the reader into thinking that we can do a similar thing for Arabic - have a "base" Arabic and an `arabic-ext`. But we can't.
* The reason we can't do that is because codepoints in different nam files end up in different fonts. So if "ب" is in `arabic` and "ࢥ" is in `arabic-ext`, they won't join together, because the "ب" will be in one font and one shaping run and  "ࢥ" will be in another font and another shaping run.
* Actually, this is *already* a problem with `latin` and `latin-ext`. You won't get any kerning in the pair "vō" because each glyph will be in a separate font. But nobody has noticed this yet, or if they have, they haven't cared.
* Another potential solution would be to have `arabic` contain just "base" Arabic and `arabic-ext` to have *both* base and extended Arabic codepoints. But if you have both fonts in CSS rules, browsers won't necessarily do the right thing. They may still grab a "ب" from one font and a "ࢥ" from another. Annoying.
* In this situation, given that only a few fonts will have a good number of extended Arabic characters, and given that much of the extended Arabic set doesn't really add too many bytes to a well-engineered font anyway (whether you're using components, or decomposing glyphs into marks and bases), I think the best solution to this issue is just to throw every Arabic script codepoint into `arabic_unique-glyphs.nam`.
* More generally, every Unicode codepoint should be covered by a nam file and we should test whether or not that's true.

**Comment by LornaSIL** [comment]
Last week I came up with this tentative new `.nam` list. I added things that we believe are important like LRO, RLO, POP, some Latin characters that are used within Arabic script such as digits U+0030...U+0039 (used in Africa), some punctuation, etc.

The main thing it doesn't cover that you are suggesting are the ligatures in the Presentation Form Blocks (such as U+FBF0 ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM ISOLATED FORM).

Is this helpful? Should I add in the ligatures so it's complete?
[arabic_unique-glyphsLE.txt](https://github.com/googlefonts/glyphsets/files/10482419/arabic_unique-glyphsLE.txt)

(Renamed `.txt` since Github wouldn't allow `.nam`.)
